name: http_platforms
description: A versatile HTTP networking package for Dart/Flutter that supports Web, Android, and iOS. Simplify API requests with cross-platform compatibility.
platforms:
  android:
  ios:
  web:
version: 1.0.0
repository: https://github.com/quyetvox/http_platforms
homepage: https://qavox.site/

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  # path: ^1.8.0
  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
