name: http_platforms
description: A starting point for Dart libraries or applications.
platforms:
  android:
  ios:
  web:
version: 1.0.0
repository: https://github.com/VoQuyt/http_platforms
homepage: https://qavox.site/

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  # path: ^1.8.0
  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
